In [1]:
!pip install --upgrade --user hmmlearn
from hmmlearn import hmm
import numpy as np
from sklearn.metrics import accuracy_score
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from sklearn.metrics import confusion_matrix
from scipy.stats import multivariate_normal
import math

Requirement already up-to-date: hmmlearn in /root/.local/lib/python3.6/site-packages (0.2.3)


In [0]:
#EDIT DATASETS HERE 
#USE DATASET VARIABLE FOR FINAL DATASET
dataset=pd.read_csv('Monday-WorkingHours.pcap_ISCX.csv')
dataset_2=pd.read_csv('Tuesday-WorkingHours.pcap_ISCX.csv')
dataset_1=pd.read_csv('Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv')
#dataset=pd.read_csv('Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv')
#dataset=pd.read_csv('Wednesday-workingHours.pcap_ISCX.csv')
#dataset=pd.read_csv('Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv')

In [3]:
#CONCATENATE DATASETS
dataset=dataset.append(dataset_1, ignore_index= True)
dataset=dataset.append(dataset_2, ignore_index= True)
#dataset=dataset.append(dataset_3, dataset_4,ignore_index=True)
#dataset=dataset.append(dataset_4, ignore_index=True)
dataset

Destination Port   Flow Duration  ...   Idle Min   Label
0                    49188               4  ...          0  BENIGN
1                    49188               1  ...          0  BENIGN
2                    49188               1  ...          0  BENIGN
3                    49188               1  ...          0  BENIGN
4                    49486               3  ...          0  BENIGN
...                    ...             ...  ...        ...     ...
1262289                 53             155  ...          0  BENIGN
1262290              59317             110  ...          0  BENIGN
1262291                 53             166  ...          0  BENIGN
1262292              54726              81  ...          0  BENIGN
1262293                 53             202  ...          0  BENIGN

[1262294 rows x 79 columns]

In [4]:
n_features=40
dataset.head()
rows,cols=dataset.shape
rows, cols

(1262294, 79)

In [0]:
#removing NaN's and np.inf from the dataset
#df[df==np.inf]=np.nan 
#df.fillna(df.mean(), inplace=True)

In [0]:
dataset[dataset==np.inf]=np.nan
dataset.fillna(0,inplace=True)

In [0]:
x_dataset=dataset.iloc[:, 0:n_features]
y=dataset.iloc[:, cols-1]

In [8]:
le=LabelEncoder()
y_encoded=le.fit_transform(y)
le.classes_

array(['BENIGN', 'FTP-Patator', 'PortScan', 'SSH-Patator'], dtype=object)

In [9]:
classes=le.classes_
x=[0 for j in range(0,len(classes))]
for i in range(0, len(classes)):
  class_string=classes[i]
  x[i]=dataset[dataset.iloc[:,cols-1]== class_string] 
x=[x[i].iloc[:,0:n_features] for i in range(0,len(classes))]
x[0].shape

(1089529, 40)

In [0]:
scaler=MinMaxScaler()
x_dataset_scaled=scaler.fit_transform(x_dataset)
for i in range(0,len(classes)):
  x[i]=scaler.fit_transform(x[i])

In [0]:
x_train,x_test_real,y_train,y_test=train_test_split(x_dataset_scaled, y_encoded, test_size=0.3)

In [12]:
n_states=3
T=10
n_attacks=len(classes)
n_attacks

4

In [0]:
model=[hmm.GaussianHMM(n_states) for i in range(0,n_attacks)]
for i in range(0,n_attacks):
  model[i].fit(x[i])

In [0]:
def forward(B,A,pi):
  alpha = [[[0 for i in range(n_states)] for j in range(len(x_test))] for k in range(0,n_attacks)] 
  for k in range(0,n_attacks):
    for i in range(0,n_states):
      alpha[k][0][i]=pi[k][i]*B[k][0][i]
  sum=0
  for k in range(0,n_attacks):
    for t in range(0,len(x_test)-1):
      for j in range (0, n_states):
        for i in range(0,n_states):
          sum=sum+alpha[k][t][i]*A[k][i][j]
        sum=sum*B[k][t+1][j]
        alpha[k][t+1][j]=sum
      sum=0 #i think there is one indent extra here. please recheck.
  prob_obs=[0 for k in range(0,n_attacks)]
  prob=0
  for k in range(0,n_attacks):
    for i in range(0,n_states):
      prob=prob+alpha[k][len(x_test)-1][i]
    prob_obs[k]=prob
    prob=0
  return prob_obs

In [15]:
index=0
n_times=int(len(x_test_real)/T)
y_pred=[1 for i in range(0,len(x_test_real))]
for T_obs in range(0,n_times):
  x_test=x_test_real[index:index+T,:]
  B=[model[i].predict_proba(x_test) for i in range(0,n_attacks)]
#B=[model[i]._compute_log_likelihood(x_test) for i in range(0,n_attacks)]
  A=[model[i].transmat_ for i in range(0,n_attacks)]
  pi=[model[i].startprob_ for i in range(0,n_attacks)]
  prob_obs=forward(B,A,pi)
  #print(prob_obs)
#ASSIGN LABELS
  pred_label=prob_obs.index(max(prob_obs))
  for i in range(index, index+T):
    y_pred[i]=pred_label
  index=index+T
len(y_pred)

378689

In [16]:
print(confusion_matrix(y_test,y_pred))
accuracy_score(y_test,y_pred)

[[191790  18364      0 116522]
 [  1350     93      0    937]
 [ 32091   1844      0  13947]
 [   969     68      0    714]]


0.5085888420313238